### PR TITLE
Add some helpers and indirect functions

### PR DESCRIPTION
**Pull request by amber8706**
Add types long: TSizeLong, TPointLong.
Changet types: TRect, TBox

Wrappers: DrawWindowIndirect, DrawButtonIndirect
New types for wrappers: TRGBColor, LOGWINDOW, LOGBUTTON

And some helpers functions

### CODE REVIEW

**Comment by vapaamies** [comment]
Only [Borland/Embarcadero styled](http://edn.embarcadero.com/article/10280) sources are [acceptable](http://forum.cantorsys.com/viewtopic.php?pid=512#p512).

**Comment by Mazdaywik** [comment]
@vapaamies, на GitHub замечания принято оставлять через ревью. Для этого нужно зайти на вкладку «Files changed», нажать на «Review changes↓» и выбрать переключатель «Request changes».

**Comment by Mazdaywik** [comment]
@amber8706, для выделения имён типов в тексте pull request’а их нужно окружать знаками обратной кавычки (на букве «ё»):
```Markdown
Add types long: `TSizeLong`, `TPointLong`.
Changet types: `TRect`, `TBox`.
```
даст:
> Add types long: `TSizeLong`, `TPointLong`.
> Changet types: `TRect`, `TBox`.

**Comment by amber8706** [comment]
> Only [Borland/Embarcadero styled](http://edn.embarcadero.com/article/10280) sources are [acceptable](http://forum.cantorsys.com/viewtopic.php?pid=512#p512).

"3.7 Type Declarations
All type declarations should begin with the letter T, and should follow the same capitalization specification laid out in the beginning of this section, or in the section on class declarations."

Types:   KolibriChar, PKolibriChar, PPKolibriChar  - without T
---------------------------------------------------------------------
Declaration of procedures, in the style:

{-1} procedure TerminateThread; stdcall

Does not comply with paragraph 4.3: 
 "You should ALWAYS indent TWO spaces for ALL indentation levels...." (There are few exceptions. The reserved words unit, users, type, interface, implementation, initialization and finalization)
---------------------------------------------------------------------
NOTE: In Delphi, it is common to write Assembly code using capital letters (code examples in the System and SysUtils modules)
---------------------------------------------------------------------
4.4 Continuation Lines
Lines should be limited to 80 columns. Lines longer than 80 columns should be broken into one or more continuation lines, as needed. For exsample:

procedure DrawWindow(Left, Top, Right, Bottom: LongInt; Caption: PKolibriChar;
  BackColor, Style, CapStyle: LongWord); stdcall;
---------------------------------------------------------------------
5.2 Single-Line Comments
A single-line comment consists of the characters // followed by text.

INCORRECT:
{-1}      procedure TerminateThread; stdcall;

CORRECT:
   //-1    
   procedure TerminateThread; stdcall;
==========================================

Дальше лень писать... Соблюдайте сами те правила, в которые тыкаете других! И да, если вам что-то не нравится - укажите место в коде, а не ссылку на правила!

**Comment by amber8706** [comment]
Only [Borland/Embarcadero styled](http://edn.embarcadero.com/article/10280) sources are [acceptable](http://forum.cantorsys.com/viewtopic.php?pid=512#p512).

3.7 Type Declarations
All type declarations should begin with the letter T, and should follow the same capitalization specification laid out in the beginning of this section, or in the section on class declarations.

Types:   KolibriChar, PKolibriChar, PPKolibriChar  - without T
==============================================================
Declaration of procedures, in the style:

{-1} procedure TerminateThread; stdcall


Does not comply with paragraph 4.3
 You should ALWAYS indent TWO spaces for ALL indentation levels.... (There are few exceptions. The reserved words unit, users, type, interface, implementation, initialization and finalization)
===============================================================
NOTE: In Delphi, it is common to write Assembly code using capital letters (code examples in the System and SysUtils modules)
===============================================================
4.4 Continuation Lines
Lines should be limited to 80 columns. Lines longer than 80 columns should be broken into one or more continuation lines, as needed. For exsample:

procedure DrawWindow(Left, Top, Right, Bottom: LongInt; Caption: PKolibriChar; <newline>
  BackColor, Style, CapStyle: LongWord); stdcall;
===============================================================
5.2 Single-Line Comments
A single-line comment consists of the characters // followed by text.

INCORRECT:
{-1}      procedure TerminateThread; stdcall;

CORRECT:
   //-1    
   procedure TerminateThread; stdcall;
==========================================

Дальше лень писать... Соблюдайте сами те правила, в которые тыкаете других! И да, если вам что-то не нравится - укажите место в коде, а не ссылку на правила! 

P.S. Что GitHub сделал с текстом? Почему некоторые его куски,  он выделил жирным?

**Comment by vapaamies** [comment]
As I [wrote](http://forum.cantorsys.com/viewtopic.php?pid=643#p643) on the forum, helper functions should be placed in `KolibriHelpers` unit. Only RGB color function is really useful.

**Pull request closed without merging**
